arch: NestedUNet
batch_size: 4
dataset: data
deep_supervision: false
early_stopping: -1
epochs: 160
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 256
input_w: 256
loss: BCEDiceLoss
lr: 0.01
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: data_NestedUNet_woDS
nesterov: false
num_classes: 1
num_workers: 0
optimizer: SGD
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 1.0e-05
